---
title: "Project Proposal"
author: "Bobby Lumpkin, Archit Datar, Lauren Contard, Haihang Wu, Yue Li"
output:
  pdf_document: default
  html_document: default
bibliography: project_proposal.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Part 1: Introduction and description of the data.

Our project aims to explore whether and how mainstream news media in the U.S. plays a role in the polarization of public's attitudes and behaviors in response to COVID-19. Elite communication, such as White House briefings and politicians' Tweets, has been found to increase the polarization between left-leaning and right-leaning public in terms of attitudes and behaviors in response to COVID-19. However, it is still unknown whether news media amplify or narrow down the effects of elite communication on polarization. 

To answer this question, we analyze the content of news articles about elite communication about COVID-19. We collected news articles from ten news media, including newspapers (i.e., New York Times, Washington Post, Wall Street Journal, and USA Today) and cable network news (i.e., ABC News, NBC News, CBS News, CNN, Fox News, and MSNBC News).To obtain the news articles, we searched the keywords in the GDELT database that monitors the world's broadcast, print, and web news from every country in more than 100 languages. We used two sets of keywords to capture the news articles about the White House responses to COVID-19. The first set of keywords were used to query White House, including "white house", "trump", "coronavirus task force", "press secretary", "McEnany", "vice president", and "pence". The second set of keywords were used to query press briefing, including "white house briefing", "coronavirus briefing", "press conference", "task force briefing", "news briefing", "press briefing", "daily briefing", "weekly briefing", and "news conference". Both sets of keywords were used in searching for articles that mentioned "covid" or "coronavirus" at least three times. The GDELT database returned 8588 news articles that met these criteria from January 20, 2020 to September 29, 2020. Part of these articles that were captured by the keywords are not relevant to the topic of this project and therefore were removed from the list. For example, an NBC news on April 30, 2020 titled "Biden calls on Trump to lower White House flag to honor coronavirus victims" was captured through the keywords search but not relevant to the topic of this project. Another example is titled "US has potential to be next epicenter of the coronavirus pandemic, WHO spokesperson says" from CNN news on March 24, 2020. The news covered a press conference held by WHO in which they mentioned the White House, but it is not relevant to the topic of this project. Another article that was removed from the list is titled "Trump is sending a hospital ship to New York, governor says" from CNN News on March 18, 2020. Some news articles that were published in Spanish were also removed from the list. After cleaning these articles, our final list includes 8013 news articles. 

We then used the Python package "Scrapy" to scrape the full text of these articles. We prepared two sets of full text: one is at the article-level, and the other is at the paragraph-level. The article-level full text will be used for differentiating relevant articles from irrelevant articles. Though we have removed some irrelevant articles from simple eyeballing, a more thorough filtering through binary classification will help us get a cleaner dataset. The paragraph-level dataset will be used for content classification. We will randomly select 2000 paragraphs and manualy label them based on the Extended Parallel Processing Model (EPPM) (@witte1992putting; @witte1994fear). The EPPM framework predicts that in order to effectively persuade people to adopt a recommended health practice, the messages need to invoke certain levels of perception of both threats and efficacies. Therefore, we manually labeled our samples into the following categories: (1) threats/impacts, (2) responses/actions, (3) severity, (4) susceptibility, (5) self-efficacy, (6) external efficacy, (7) response efficacy, (8) public health, (9) economy, (10) education, (11) political evaluation, (12) racial conflict, (13) international relations/foreign policies, (14) positive, (15) negative. The first 13 categories will be labeled as either 0(No) or 1(Yes). The 14 and 15 categories will be labeled as three levels 0(none), 1(some part of the paragraph is positive/negative OR the overall sentiment of the paragraph is mildly positive/negative), or 2(most parts of the paragraph are positive/negative OR the overall sentiment of the paragraph is extremely/intensively positive/negative). All the 15 categories are not mutually exclusive. That is, one paragraph can be labeled as multiple categories. 

## Part 2: A detailed problem statement (question of interest).

The overarching goal of the project is to see whether news media amplify or narrow down the polarization in health attitudes and behaviors. Polarization is far more than just within political issues. Research has found that there is polarization between Democrats and Republicans in their health-related attitudes and behaviors. For example, de Bruin, Saw, and Goldman (2020) found that Democrats perceived higher risks associated with COVID-19 than Republicans (@de2020political).Similarly, van Holm, Monaghan, Shahar, Messhina, and Surprenant (2020) found that Democrats made fewer trips than Republicans and were more likely to change their behaviors in ways recommended by public health experts and governors (@van2020impact). Though scholars have found associatations between media consumption and polarization in health-related atttitudes and behaviors, there lacks empirical evidence of the mechanisms of how news media will play a role in the polarization process. This project will fill in the gap by analyzing the content of the news articles and incorporating daily surveys that keep tracking American's health attitudes and behaviors (this part will not be included in the final project for STAT6500).